[default]
workshop = [
    "450814997",  # CBA_A3
    "3499977893", # Advanced Dev Tools
    "623475643",  # 3DEN Enhanced
    "463939057",  # ACE
    "3393234585",  # The Moon
    "1779063631", # Zeus Enhanced
]
presets = []
dlc = []
optionals = []
parameters = []

[ace]
extends = "default"
workshop = [
    "463939057", # ACE
]
