[sqf.command_case]
options.ignore = [
    "objNull", # Ignoring wiki check for this, throws warning which would break code in game for module functions
]

[sqf.banned_commands]
options.banned = [
    "spawn", # Scheduled should be avoided whenever possible
    "execVM", # Script files should never be run directly, they should be functions
    "remoteExec", # CBA events should be used for networking
]
