name = "Extraterra"
author = "Luriss"
prefix = "exterra"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_exterra.png",
    "logo_exterra_ca.paa",
    "LICENSE.md",
    "README.txt",
]
exclude = []

[properties]
author = "Luriss"
